version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media  # Ensure this is indented correctly and in proper YAML format
    ports:
      - "8000:8000"